sudo: required
services:
  -docker

before_install:
  - docker build -t 24051966/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 24051966/docker-react npm run test

deploy:
  edge: "true"
  provider: elasticbeanstalk
  region: us-west-2
  app: "app"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-167051870968"
  bucket_path: "docker"
  on:
    branch: master